## La libreria Numpy


In [1]:
import numpy as np

## Creacion de Arrays

In [2]:
A = np.array([[1,2], [4,3]])

In [3]:
print(A)

[[1 2]
 [4 3]]


In [4]:
B = np.ones([3,2])
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
C = np.identity(5)
print(C)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [6]:
G = np.arange(1,11,0.5)
print(G)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5]


In [7]:
H = np.linspace(1,10,5) #Crear arrays con puntos medios: Inicio | Final | Cantidad de puntos medios
print(H)

[ 1.    3.25  5.5   7.75 10.  ]


In [8]:
R = np.random.random([3,2]) #Crear arrays con valores aleatorios entre 0 y 1 de tamaño 3x2
print(R)

[[0.00310612 0.6038633 ]
 [0.48096182 0.76385542]
 [0.27133738 0.74614489]]


## Caracteristicas de un Array

In [9]:
R.dtype #Tipo de dato del array


dtype('float64')

In [10]:
R.ndim #Número de dimensiones del array


2

In [11]:
R.shape #Dimensiones del array (filas, columnas)


(3, 2)

In [12]:
R.size #Número total de elementos del array

6

### Obtener y modificar elementos de un array

In [13]:
Ejemplo = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(Ejemplo)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
Ejemplo[2,2] #Obtener el elemento de la fila 2, columna 2 (índices empiezan en 0)

np.int64(9)

In [15]:
Ejemplo[2,0]=50 #Modificar el elemento de la fila 2, columna 0
print(Ejemplo)

[[ 1  2  3]
 [ 4  5  6]
 [50  8  9]]


In [16]:
Ejemplo[:2,:2] #Obtener un subarray (filas 0 y 1, columnas 0 y 1)

array([[1, 2],
       [4, 5]])

In [17]:
Ejemplo[:2,1:3] #Obtener un subarray (filas 0 y 1, columnas 1 y 2)

array([[2, 3],
       [5, 6]])

### Filtrando elementos de un Array

In [ ]:
AR=np.array([[1,7,3,4],[2,12,4,1],[2,9,7,8]])
print(AR)
AR[(AR%2==0) & (AR>4)] #Obtener los elementos pares mayores que 4


[[ 1  7  3  4]
 [ 2 12  4  1]
 [ 2  9  7  8]]


array([12,  8])

In [ ]:
AR[(AR%2==0) | (AR%3==0)] #Obtener los elementos pares o múltiplos de 3

array([ 3,  4,  2, 12,  4,  2,  9,  8])

In [ ]:
F1 = [1,2,3,4]
M = np.array([F1,[3*k for k in F1], [(3*k)**2 for k in F1]]) #Crear un array a partir de listas
print(M)
print('El numero de elementos impares es: ',M[M%2!=0].size) # Contar los elementos impares del array

[[  1   2   3   4]
 [  3   6   9  12]
 [  9  36  81 144]]
El numero de elementos impares es:  6


### Dimensiones da arrays

In [ ]:
AG = np.array([7,2,9,10]) #Array de una dimensión
print(AG)

[ 7  2  9 10]


In [23]:
BG = np.array([[5,2,5,6],[7,8,3,4]]) #Array de dos dimensiones
print(BG)

[[5 2 5 6]
 [7 8 3 4]]


### Eliminar y añadir elementos

In [30]:
print(f"AG(original): {AG}")
AG = np.delete(AG,1) #Eliminar el elemento en la posición 1 del array AG
print(f"AG(modificado): {AG}")

AG(original): [ 7  9 10]
AG(modificado): [ 7 10]
