## La libreria Numpy


In [2]:
import numpy as np

## Creacion de Arrays

In [3]:
A = np.array([[1,2], [4,3]])

In [4]:
print(A)

[[1 2]
 [4 3]]


In [5]:
B = np.ones([3,2])
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
C = np.identity(5)
print(C)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
G = np.arange(1,11,0.5)
print(G)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5]


In [ ]:
H = np.linspace(1,10,5) #Crear arrays con puntos medios: Inicio | Final | Cantidad de puntos medios
print(H)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
R = np.random.random([3,2]) #Crear arrays con valores aleatorios entre 0 y 1 de tamaño 3x2
print(R)

[[0.55758596 0.98413117]
 [0.24935129 0.44715538]
 [0.64250049 0.35808064]]


## Caracteristicas de un Array

In [ ]:
R.dtype #Tipo de dato del array


dtype('float64')

In [ ]:
R.ndim #Número de dimensiones del array


2

In [ ]:
R.shape #Dimensiones del array (filas, columnas)


(3, 2)

In [ ]:
R.size #Número total de elementos del array

6

### Obtener y modificar elementos de un array

In [16]:
Ejemplo = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(Ejemplo)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
Ejemplo[2,2] #Obtener el elemento de la fila 2, columna 2 (índices empiezan en 0)

np.int64(9)

In [18]:
Ejemplo[2,0]=50 #Modificar el elemento de la fila 2, columna 0
print(Ejemplo)

[[ 1  2  3]
 [ 4  5  6]
 [50  8  9]]


In [ ]:
Ejemplo[:2,:2] #Obtener un subarray (filas 0 y 1, columnas 0 y 1)

array([[1, 2],
       [4, 5]])

In [21]:
Ejemplo[:2,1:3] #Obtener un subarray (filas 0 y 1, columnas 1 y 2)

array([[2, 3],
       [5, 6]])