## La libreria Numpy


In [2]:
import numpy as np

## Creacion de Arrays

In [3]:
A = np.array([[1,2], [4,3]])

In [4]:
print(A)

[[1 2]
 [4 3]]


In [5]:
B = np.ones([3,2])
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
C = np.identity(5)
print(C)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
G = np.arange(1,11,0.5)
print(G)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5]


In [8]:
H = np.linspace(1,10,5) #Crear arrays con puntos medios: Inicio | Final | Cantidad de puntos medios
print(H)

[ 1.    3.25  5.5   7.75 10.  ]


In [9]:
R = np.random.random([3,2]) #Crear arrays con valores aleatorios entre 0 y 1 de tamaño 3x2
print(R)

[[0.82959795 0.40391432]
 [0.35183135 0.76906636]
 [0.02849277 0.50188898]]


## Caracteristicas de un Array

In [10]:
R.dtype #Tipo de dato del array


dtype('float64')

In [11]:
R.ndim #Número de dimensiones del array


2

In [12]:
R.shape #Dimensiones del array (filas, columnas)


(3, 2)

In [13]:
R.size #Número total de elementos del array

6

### Obtener y modificar elementos de un array

In [14]:
Ejemplo = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(Ejemplo)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
Ejemplo[2,2] #Obtener el elemento de la fila 2, columna 2 (índices empiezan en 0)

np.int64(9)

In [16]:
Ejemplo[2,0]=50 #Modificar el elemento de la fila 2, columna 0
print(Ejemplo)

[[ 1  2  3]
 [ 4  5  6]
 [50  8  9]]


In [17]:
Ejemplo[:2,:2] #Obtener un subarray (filas 0 y 1, columnas 0 y 1)

array([[1, 2],
       [4, 5]])

In [18]:
Ejemplo[:2,1:3] #Obtener un subarray (filas 0 y 1, columnas 1 y 2)

array([[2, 3],
       [5, 6]])

### Filtrando elementos de un Array

In [19]:
AR=np.array([[1,7,3,4],[2,12,4,1],[2,9,7,8]])
print(AR)
AR[(AR%2==0) & (AR>4)] #Obtener los elementos pares mayores que 4


[[ 1  7  3  4]
 [ 2 12  4  1]
 [ 2  9  7  8]]


array([12,  8])

In [20]:
AR[(AR%2==0) | (AR%3==0)] #Obtener los elementos pares o múltiplos de 3

array([ 3,  4,  2, 12,  4,  2,  9,  8])

In [21]:
F1 = [1,2,3,4]
M = np.array([F1,[3*k for k in F1], [(3*k)**2 for k in F1]]) #Crear un array a partir de listas
print(M)
print('El numero de elementos impares es: ',M[M%2!=0].size) # Contar los elementos impares del array

[[  1   2   3   4]
 [  3   6   9  12]
 [  9  36  81 144]]
El numero de elementos impares es:  6


### Dimensiones da arrays

In [22]:
AG = np.array([7,2,9,10]) #Array de una dimensión
print(AG)

[ 7  2  9 10]


In [23]:
BG = np.array([[5,2,5,6],[7,8,3,4]]) #Array de dos dimensiones
print(BG)

[[5 2 5 6]
 [7 8 3 4]]


### Eliminar y añadir elementos

In [24]:
print(f"AG(original): {AG}")
AG = np.delete(AG,1) #Eliminar el elemento en la posición 1 del array AG
print(f"AG(modificado): {AG}")

AG(original): [ 7  2  9 10]
AG(modificado): [ 7  9 10]


In [25]:
JG = np.delete(BG,0,axis=1) #Eliminar la columna 0 del array BG
print(JG) #axis=0 para filas, axis=1 para columnas

[[2 5 6]
 [8 3 4]]


In [26]:
EG = np.append(AG,[6,7]) #Añadir elementos al final del array AG
print(EG) #Mostrar el array resultante


[ 7  9 10  6  7]


In [ ]:
EG = np.append(BG,[[6],[7]],axis=1) #Añadir una columna al final del array BG
print(EG) #axis=0 para filas, axis=1 para columnas

[[5 2 5 6 6]
 [7 8 3 4 7]]


In [31]:
AG = np.linspace(1,36,36) #Crear un array con 36 elementos entre 1 y 36
print(f"array original: \n{AG}")
AG = AG.reshape(6,6) #Cambiar la forma del array AG a 6x6
print(f"array reconfigurado: \n{AG}")

array original: 
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.]
array reconfigurado: 
[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]
 [13. 14. 15. 16. 17. 18.]
 [19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30.]
 [31. 32. 33. 34. 35. 36.]]


## Suma,Resta,multiplicacion y division

In [39]:
PR = np.array([[1,2],[3,4]])
SR = np.array([[5,6],[7,8]])
print(f"PR:\n {PR}")
print(f"SR:\n {SR}")


PR:
 [[1 2]
 [3 4]]
SR:
 [[5 6]
 [7 8]]


In [40]:
print(f"PR + SR =\n {PR + SR}") #Suma de arrays
print("------------------------")
print(f"np.add(PR,SR) =\n {np.add(PR,SR)}") #Suma de arrays usando la función add

PR + SR =
 [[ 6  8]
 [10 12]]
------------------------
np.add(PR,SR) =
 [[ 6  8]
 [10 12]]


In [41]:
print(f"PR - SR =\n {PR - SR}") #Resta de arrays
print("------------------------")
print(f"np.subtract(PR,SR) =\n {np.subtract(PR,SR)}") #Resta de arrays usando la función subtract

PR - SR =
 [[-4 -4]
 [-4 -4]]
------------------------
np.subtract(PR,SR) =
 [[-4 -4]
 [-4 -4]]


In [42]:
print(f"PR * SR =\n {PR * SR}") #Multiplicación de arrays
print("------------------------")
print(f"np.multiply(PR,SR) =\n {np.multiply(PR,SR)}") #Multiplicación de arrays usando la función multiply

PR * SR =
 [[ 5 12]
 [21 32]]
------------------------
np.multiply(PR,SR) =
 [[ 5 12]
 [21 32]]


In [43]:
print(f"PR / SR =\n {PR / SR}") #División de arrays
print("------------------------")
print(f"np.divide(PR,SR) =\n {np.divide(PR,SR)}") #División de arrays usando la función divide

PR / SR =
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
------------------------
np.divide(PR,SR) =
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [44]:
print(f"Tambien se pueden usar operadores como +, -, *, / directamente con los arrays.")
print(f"PR * 7 =\n {PR * 7}") #Multiplicación de un array por un escalar

Tambien se pueden usar operadores como +, -, *, / directamente con los arrays.
PR * 7 =
 [[ 7 14]
 [21 28]]


### Operaciones matematicas sobre los elementos de un array

In [45]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.power(M,2) #Elevar al cuadrado cada elemento del array M 

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [46]:
np.log(M) #Logaritmo natural de cada elemento del array M

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [47]:
np.sqrt(M) #Raíz cuadrada de cada elemento del array M

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [48]:
np.cos(M) #Coseno de cada elemento del array M

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [49]:
np.tan(M) #Tangente de cada elemento del array M

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

### Operaciones estadisticas con arrays

In [50]:
R = np.random.random([5])
print(R)

[0.28035371 0.37360604 0.31714102 0.99833151 0.36538284]


In [51]:
np.mean(R) #Media de los elementos del array R

np.float64(0.4669630271039513)

In [52]:
np.median(R) #Mediana de los elementos del array R

np.float64(0.36538284364949725)

In [53]:
np.std(R) #Desviación estándar de los elementos del array R

np.float64(0.26782688271904076)

In [54]:
np.max(R) #Valor máximo del array R

np.float64(0.9983315119965754)

In [55]:
np.min(R) #Valor mínimo del array R

np.float64(0.280353713134446)

### Algebra lineal con Arrays

In [61]:
a = np.array([1,2,3])
b = np.array([5,4,2])
c = np.array([2,5,6])

np.dot(a,b) #Producto punto entre los arrays a y b

np.int64(19)

In [63]:
np.cross(a,b) #Producto cruz entre los arrays a y b

array([-8, 13, -6])

In [64]:
m = np.array([a,b,c])
np.linalg.inv(m) #Matriz inversa de la matriz m

array([[ 1.07692308e+00,  2.30769231e-01, -6.15384615e-01],
       [-2.00000000e+00, -1.63268092e-17,  1.00000000e+00],
       [ 1.30769231e+00, -7.69230769e-02, -4.61538462e-01]])

In [66]:
np.linalg.eigvals(m) #Valores propios de la matriz m

array([10.34832364+0.j        ,  0.32583818+1.07241391j,
        0.32583818-1.07241391j])

In [67]:
np.trace(m) #Traza de la matriz m

np.int64(11)

In [68]:
np.transpose(m) #Transpuesta de la matriz m

array([[1, 5, 2],
       [2, 4, 5],
       [3, 2, 6]])

In [70]:
A = np.array([[1,2],[3,4]])
B = np.array([5,6])
np.linalg.solve(A,B)

array([-4. ,  4.5])